<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20170202105814 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema): void {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE netlogix_cqrs_log_commandlogentry CHANGE command command LONGBLOB NOT NULL COMMENT '(DC2Type:objectblob)', CHANGE exception exception LONGBLOB NOT NULL COMMENT '(DC2Type:objectblob)'");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema): void {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE netlogix_cqrs_log_commandlogentry CHANGE command command LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT '(DC2Type:object)', CHANGE exception exception LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT '(DC2Type:object)'");
	}
}