TYPO3:
  Flow:
    persistence:
      doctrine:
        # DBAL custom mapping types can be registered here
        dbal:
          mappingTypes:
            'objectblob':
              dbType: 'blob'
              className: 'Netlogix\Cqrs\Doctrine\Type\ObjectType'
