
Neos:
  Flow:
    persistence:
      doctrine:
        dbal:
          mappingTypes:
            objectblob:
              dbType: blob
              className: Netlogix\Cqrs\Doctrine\Type\ObjectType
